const RATE_USD_TO_EUR = 0.95

import { useState, useEffect } from 'react'
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import {
  Grid,
  Button,
  Typography,
  Divider,
  Box,
  Container,
  Stack,
  FormControl,
  TextField,
  Card,
  CardContent,
} from "@mui/material";
// import SearchIcon from "@mui/icons-material/Search";
import SelectCustom from "../components/SelectCustom";
import TokensTable from "../components/TokensTable";
import HCarousel from "../components/HCarousel";
import HeadCrumb from "@/components/Header/HeadCrumb";
import tezosLogo from "../assets/images/tezos_gradient.svg";
import searchIcon from "../assets/iconSvg/searchIcon.svg";
import TypingEffect from "../components/others/typingEffect";
import Background from "../components/others/background";
// import ScanIcon from "@/assets/iconSvg/ScanIcon.svg";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { useRouter } from "next/router";
import { HomeResponse, MiscellaneousResponse } from '../endpoints/API';
import HomeEndpoint from '../endpoints/HomeEndpoint';
import MiscellaneousEndpoint from '../endpoints/MiscellaneousEndpoint';
import { formatPrice, formatToken } from '../utils/format'
import useWindowSize from '../hooks/useWindowSize'

export async function getServerSideProps({ locale }: any) {
  const miscResponse = await MiscellaneousEndpoint({})
  const homeResponse = await HomeEndpoint({ pageSize: 100 })
  console.log(homeResponse, miscResponse)

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
      miscResponse,
      homeResponse,
      iniSeconds: Math.floor((+(new Date(homeResponse.stats.lastBlockDate)) - +(new Date())) / 1000),
    },
  };
}

export default function Home({ homeResponse, miscResponse, iniSeconds, _nextI18Next }:
  { homeResponse: HomeResponse, miscResponse: MiscellaneousResponse, iniSeconds: number, _nextI18Next: any }
) {
  const { t } = useTranslation("common");
  const router = useRouter();
  const {locale} = router
  const [seconds, setSeconds] = useState(iniSeconds)
  useEffect(() => {
    let i = setInterval(() => setSeconds(seconds => seconds - 1), 1000)
    return () => clearInterval(i)
  }, [])
  const windowWidth = useWindowSize().width;
  const [collectionCriteria, setCollectionCriteria] = useState('trending')
  const [tokenCriteria, setTokenCriteria] = useState('byCap')

  return (
    <>
      <Head>
        <title>BetterScan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/*<HeadCrumb /> Temporarely disabled*/}
        <Header />
        <Box className="searchBlock">
          <Container maxWidth="xl">
            <Typography
              variant="h5"
              align="center"
              color="text.secondary"
              paragraph
            >
              {t("animTitle")} <span className="displayIfSmall"><br /></span>
              <TypingEffect strings={_nextI18Next.initialI18nStore[locale].common.anim} /> <br />
              {t("animTitle2")}
            </Typography>
            <form onSubmit={() => {alert('Search!')}} className="searchBlock-form">
              <TextField
                hiddenLabel
                id="filled-hidden-label-small"
                defaultValue=""
                placeholder={t("inputPlaceholder") + (windowWidth > 500 ? t("inputPlaceholderIfLarge") : '')}
                fullWidth
                sx={{ ml: 0 }}
              ></TextField>
              <span className="scanIcon">{/* <ScanIcon /> */}</span>
              <Button
                type="submit"
                variant="contained"
                className="mainSearchButton"
              >
                <Image src={searchIcon} width={40} alt="Research icon" style={{zIndex: "1"}} />
              </Button>
            </form>
          </Container>
        </Box>
        <Box className="cardsModule">
          <Container maxWidth="xl">
            <Grid
              container
              rowSpacing={2}
              columnSpacing={{ xs: 1, sm: 2, md: 3 }}
            >
              <Grid item xs={12} sm={12} md={4}>
                <Box className="cardBox cardBox--info">
                  <Box className="cardBox-inner">
                    <Box className="cardBox-data">
                      <Box className="cardBox-head">
                        <Typography
                          gutterBottom
                          variant="h5"
                          className="cardBox-title"
                        >
                          {t("stat1")}
                          <b>XTZ</b>
                        </Typography>
                      </Box>
                      <Typography variant="h4" className="cardBox-price">
                        <span className="gradientText">{ formatPrice(miscResponse.xtzPrice, locale, miscResponse.rates) }</span>
                      </Typography>
                    </Box>
                    <Image
                      priority
                      src={tezosLogo}
                      width={100}
                      alt=""
                      className="cryptoLogo"
                    />
                  </Box>
                </Box>
              </Grid>
              <Grid item xs={12} sm={12} md={4}>
                <Box className="cardBox">
                  <Box className="cardBox-inner">
                    <Box className="cardBox-head">
                      <Typography
                        gutterBottom
                        variant="h5"
                        className="cardBox-title"
                      >
                        {t("stat2")}
                      </Typography>
                    </Box>
                    <Typography variant="h4" className="cardBox-price">
                      <span className="gradientText">{formatPrice(((+homeResponse.stats.normalFee / 1_000_000) * +miscResponse.xtzPrice).toString(), locale, miscResponse.rates)}</span>
                      <span className="cardBox-status">({formatToken(homeResponse.stats.normalFee, 6, locale)} XTZ)</span>
                    </Typography>
                  </Box>
                </Box>
              </Grid>
              <Grid item xs={12} sm={12} md={4}>
                <Box className="cardBox">
                  <Box className="cardBox-inner">
                    <Box className="cardBox-head">
                      <Typography
                        gutterBottom
                        variant="h5"
                        className="cardBox-title"
                      >
                        {t("stat3")}
                      </Typography>
                      {/*<span className="cardBox-status">{homeResponse.stats.lastBlockDate}</span>*/}
                    </Box>
                    <Typography variant="h4" className="cardBox-price">
                      <span className="gradientText">{t('inXSeconds', {seconds: 15 + seconds % 15})}</span>
                    </Typography>
                  </Box>
                </Box>
              </Grid>
            </Grid>
          </Container>
        </Box>
        <Box className="sliderBlock">
          <Container maxWidth="xl">
            <Box className="sectionHead">
              <Box className="sectionHead-title">{t('sectionTitleCollections')}</Box>
              <SelectCustom
                onChange={setCollectionCriteria}
                values={['trending', 'top']}
                labels={[t('criteriaTrending'), t('criteriaTop')]}
              />
            </Box>
            <HCarousel collections={homeResponse.collections[collectionCriteria]} />
          </Container>
        </Box>
        <Box className="listTableBlock">
          <Container maxWidth="xl">
            <Box className="sectionHead">
              <Box className="sectionHead-title">{t('sectionTitleTokens')}</Box>
              <SelectCustom
                onChange={setTokenCriteria}
                values={['byCap', 'byVolume']}
                labels={[t('criteriaByCap'), t('criteriaByVolume')]}
              />
            </Box>
            <TokensTable />
          </Container>
        </Box>
      </main>
    </>
  );
}
