#!/bin/sh

# Get a list of staged files before formatting
staged_files_before=$(git diff --name-only --cached)
echo "Staged:\n$staged_files_before"


cd WebApp


# Run the commands
npm run check-types
if [ $? -ne 0 ]; then
    echo "Error: npm run check-types failed. Aborting commit."
    exit 1
fi

npm run check-lint
if [ $? -ne 0 ]; then
    echo "Error: npm run check-lint failed. Aborting commit."
    exit 1
fi

npm run format
if [ $? -ne 0 ]; then
    echo "Error: npm run format failed. Aborting commit."
    exit 1
fi


cd ..


# Add the newly formatted files to the staging area
for file in $staged_files_before; do
    git add "$file"
    echo "Added: $file"
done

# Continue with the commit
exit 0
