#!/bin/sh


cd WebApp

# Run the commands
npm run check-types
if [ $? -ne 0 ]; then
    echo "Error: npm run check-types failed. Aborting commit."
    exit 1
fi

npm run check-lint
if [ $? -ne 0 ]; then
    echo "Error: npm run check-lint failed. Aborting commit."
    exit 1
fi

npm run format
if [ $? -ne 0 ]; then
    echo "Error: npm run format failed. Aborting commit."
    exit 1
fi
