#!/bin/sh


cd WebApp

# Get a list of staged files before formatting
staged_files_before=$(git diff --name-only --cached)


# Run the commands
npm run check-types
if [ $? -ne 0 ]; then
    echo "Error: npm run check-types failed. Aborting commit."
    exit 1
fi

npm run check-lint
if [ $? -ne 0 ]; then
    echo "Error: npm run check-lint failed. Aborting commit."
    exit 1
fi

npm run format
if [ $? -ne 0 ]; then
    echo "Error: npm run format failed. Aborting commit."
    exit 1
fi


# Add the newly formatted files to the staging area
for file in $staged_files_before; do
    git add "$file"
done

# Continue with the commit
exit 0
