import { HomeEndpoint } from './API'
import * as tzstats from './providers/tzstats'
import * as rpc from './providers/rpc'
import * as objkt from './providers/objkt'
import * as coinmarketcap from './providers/coinmarketcap'

const topTokens = [
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeigulbzm5x72qtmckxqvd3ksk6q3vlklxjgpnvvnbcofgdp6qwu43u",
    "ModalCell_joinRow__sUQiU": "crDAO",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Crunchy DAO",
    "Price": 0.0000091,
    "Full name": "crDAO",
    "contract address": "KT1XPFjZqCULSnqfKaaYy8hJjeY63UNSGwXg_0",
    "contract address__1": "KT1XPFjZqCULSnqfKaaYy8hJjeY63UNSGwXg",
    "token id": 0,
    "total supply": 1e+22,
    "decimals": 8,
    "Alias": "Crunchy DAO",
    "thumbnailUri": "ipfs://bafybeigulbzm5x72qtmckxqvd3ksk6q3vlklxjgpnvvnbcofgdp6qwu43u",
    "holdersCount": 1016,
    "mcap": 910_000_000.11
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmbev41h4axBqVzxsXP2NSaAF996bJjJBPb8FFZVqTvJTY",
    "ModalCell_joinRow__sUQiU": "uBTC",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "youves uBTC",
    "Price": 36_523.94000000000,
    "Full name": "LQT uBTC/tzBTC FlatYouves",
    "contract address": "KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW_2",
    "contract address__1": "KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW",
    "token id": 2,
    "total supply": 7028468715900814,
    "decimals": 12,
    "Alias": "youves uDEFI",
    "thumbnailUri": "ipfs://QmNfosyixuXVG2TGmE7FmLGZGJhK2Q9qHZicsMixsbgqH1",
    "holdersCount": 299,
    "mcap": 256_707_369.67
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://tzbtc.io/wp-content/uploads/2020/03/tzbtc_logo_single.svg",
    "ModalCell_joinRow__sUQiU": "tzBTC",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "tzBTC",
    "Price": 35_882.04000000000,
    "Full name": "tzBTC",
    "contract address": "KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn",
    "contract address__1": "KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn",
    "token id": null,
    "total supply": 1076,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 2758,
    "mcap": 38_609_075.04
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmNXQPkRACxaR17cht5ZWaaKiQy46qfCwNVT5FGZy6qnyp",
    "ModalCell_joinRow__sUQiU": "SIRS",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "Sirius",
    "Price": 0.06,
    "Full name": "SIRS",
    "contract address": "KT1AafHA1C1vk959wvHWBispY9Y2f3fxBUUo",
    "contract address__1": "KT1AafHA1C1vk959wvHWBispY9Y2f3fxBUUo",
    "token id": null,
    "total supply": 370000000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 820,
    "mcap": 22_200_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmW8sa5UygUKg58LLzK7NoEDtCRyAQU4wZh1rbpFa6j7kP",
    "ModalCell_joinRow__sUQiU": "DOGA",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "DOGAMI",
    "Price": 0.02,
    "Full name": "DOGA",
    "contract address": "KT1Ha4yFVeyzw6KRAdkzq6TxDHB97KG4pZe8",
    "contract address__1": "KT1Ha4yFVeyzw6KRAdkzq6TxDHB97KG4pZe8",
    "token id": null,
    "total supply": 1000000000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 7192,
    "mcap": 20_000_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmdqDheWwndbcxuGg6p5VyPbVvEwgCYexCQc5hJy2WZojq",
    "ModalCell_joinRow__sUQiU": "LYZI",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Lyzi",
    "Price": 0.03,
    "Full name": "Lyzi",
    "contract address": "KT1UMx7aZQWNKY9nC4LRYNsueEiGMfpcQhhD_0",
    "contract address__1": "KT1UMx7aZQWNKY9nC4LRYNsueEiGMfpcQhhD",
    "token id": 0,
    "total supply": 550000000000000,
    "decimals": 6,
    "Alias": "Lyzi",
    "thumbnailUri": "ipfs://QmdqDheWwndbcxuGg6p5VyPbVvEwgCYexCQc5hJy2WZojq",
    "holdersCount": 402,
    "mcap": 16_500_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmbvhanNCxydZEbGu1RdqkG3LcpNGv7XYsCHgzWBXnmxRd",
    "ModalCell_joinRow__sUQiU": "uUSD",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "youves uUSD",
    "Price": 1,
    "Full name": "cTEZ / uUSD  LP farm",
    "contract address": "KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW_0",
    "contract address__1": "KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW",
    "token id": 0,
    "total supply": 12556592616482945000,
    "decimals": 12,
    "Alias": "youves uUSD",
    "thumbnailUri": "ipfs://QmbvhanNCxydZEbGu1RdqkG3LcpNGv7XYsCHgzWBXnmxRd",
    "holdersCount": 3400,
    "mcap": 12_556_592.62
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmP9ZXExg9EXXFtn8uLzyqMxecWVxUDb25reBCCoCzDPdt",
    "ModalCell_joinRow__sUQiU": "dtez",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "Kord.Fi te...",
    "Price": 0.89,
    "Full name": "dTEZ/cTEZ v3 Plenty Network",
    "contract address": "KT19qWdPBRtkWrsQnDvVfsqJgJB19keBhhMX",
    "contract address__1": "KT19qWdPBRtkWrsQnDvVfsqJgJB19keBhhMX",
    "token id": null,
    "total supply": 8000000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 123,
    "mcap": 7_120_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmcqsYQn8pTxQr3P1dYpgYxQa6GQPmoBTSWQ8bpuFEuaqe",
    "ModalCell_joinRow__sUQiU": "EURL",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Lugh Euro ...",
    "Price": 1.06,
    "Full name": "EURL",
    "contract address": "KT1JBNFcB5tiycHNdYGYCtR3kk6JaJysUCi8_0",
    "contract address__1": "KT1JBNFcB5tiycHNdYGYCtR3kk6JaJysUCi8",
    "token id": 0,
    "total supply": 3500525000000,
    "decimals": 6,
    "Alias": "Lugh Euro pegged stablecoin",
    "thumbnailUri": "ipfs://QmcqsYQn8pTxQr3P1dYpgYxQa6GQPmoBTSWQ8bpuFEuaqe",
    "holdersCount": 270,
    "mcap": 3_710_556.50
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmZqvc3iVpNWnieKuCC5rvaFUAQ95pdYqkJftduVfonAxo",
    "ModalCell_joinRow__sUQiU": "dtzbtc",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "Kord.Fi tz...",
    "Price": 35_000.00000000000,
    "Full name": "Atomex tzBTC",
    "contract address": "KT1WL6sHt8syFT2ts7NCmb5gPcS2tyfRxSyi",
    "contract address__1": "KT1WL6sHt8syFT2ts7NCmb5gPcS2tyfRxSyi",
    "token id": null,
    "total supply": 97,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 69,
    "mcap": 3_395_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmYAJaJvEJuwvMEgRbBoAUKrTxRTT22nCC9RuY7Jy4L4Gc",
    "ModalCell_joinRow__sUQiU": "YOU",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "youves YOU...",
    "Price": 0.77,
    "Full name": "A Boney-Skully Gift For You",
    "contract address": "KT1Xobej4mc6XgEjDoJoHtTKgbD1ELMvcQuL_0",
    "contract address__1": "KT1Xobej4mc6XgEjDoJoHtTKgbD1ELMvcQuL",
    "token id": 0,
    "total supply": 3533287671459380700,
    "decimals": 12,
    "Alias": "youves YOU Governance",
    "thumbnailUri": "ipfs://QmYAJaJvEJuwvMEgRbBoAUKrTxRTT22nCC9RuY7Jy4L4Gc",
    "holdersCount": 1880,
    "mcap": 2_720_631.51
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmdj6n9T48LDWex8NkBMKUQJfZgardxZVdtRRibYQVzLCJ",
    "ModalCell_joinRow__sUQiU": "wWBTC",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped WBTC",
    "Price": 37_070.01000000000,
    "Full name": "cTEZ / wWBTC  LP farm",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 19,
    "total supply": 5979654498,
    "decimals": 8,
    "Alias": "Wrapped WBTC",
    "thumbnailUri": "ipfs://Qmdj6n9T48LDWex8NkBMKUQJfZgardxZVdtRRibYQVzLCJ",
    "holdersCount": 1325,
    "mcap": 2_216_658.52
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://kolibri-data.s3.amazonaws.com/logo.png",
    "ModalCell_joinRow__sUQiU": "KUSD",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "Kolibri",
    "Price": 1,
    "Full name": "Kolibri USD",
    "contract address": "KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV",
    "contract address__1": "KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV",
    "token id": 0,
    "total supply": 1.28868e+24,
    "decimals": 18,
    "Alias": "Kolibri USD",
    "thumbnailUri": "https://services.tzkt.io/v1/avatars/KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV",
    "holdersCount": 5239,
    "mcap": 1_288_678.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmb2GiHN9EjcrN29J6y9PsXu3ZDosXTv6uLUWGZfRRSzS2/smak.png",
    "ModalCell_joinRow__sUQiU": "SMAK",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "SmartLink",
    "Price": 0.0014,
    "Full name": "PLENTY / SMAK LP farm",
    "contract address": "KT1TwzD6zV3WeJ39ukuqxcfK2fJCnhvrdN1X",
    "contract address__1": "KT1TwzD6zV3WeJ39ukuqxcfK2fJCnhvrdN1X",
    "token id": null,
    "total supply": 896000000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 4632,
    "mcap": 1_254_400.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmQfHU9mYLRDU4yh2ihm3zrvVFxDrLPiXNYtMovUQE2S2t",
    "ModalCell_joinRow__sUQiU": "wUSDC",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped USDC",
    "Price": 1.01,
    "Full name": "cTEZ / wUSDC  LP farm",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 17,
    "total supply": 967101803925,
    "decimals": 6,
    "Alias": "Wrapped USDC",
    "thumbnailUri": "ipfs://QmQfHU9mYLRDU4yh2ihm3zrvVFxDrLPiXNYtMovUQE2S2t",
    "holdersCount": 2051,
    "mcap": 976_772.82
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://raw.githubusercontent.com/Plenty-DeFi/Plenty-Logo/main/PlentyTokenIcon.png",
    "ModalCell_joinRow__sUQiU": "PLENTY",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "Plenty DAO",
    "Price": 0.01,
    "Full name": "PLENTY",
    "contract address": "KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b",
    "contract address__1": "KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b",
    "token id": null,
    "total supply": 59000000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 5605,
    "mcap": 590_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmezz1ztvo5JFshHupBEdUzVppyMfJH6K4kPjQRSZp8cLq",
    "ModalCell_joinRow__sUQiU": "wWETH",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped WETH",
    "Price": 1_982.78000000000,
    "Full name": "cTEZ / wWETH  LP farm",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 20,
    "total supply": 258851288718572950000,
    "decimals": 18,
    "Alias": "Wrapped WETH",
    "thumbnailUri": "ipfs://Qmezz1ztvo5JFshHupBEdUzVppyMfJH6K4kPjQRSZp8cLq",
    "holdersCount": 1221,
    "mcap": 513_245.16
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmQs2XZLFszq5npkYdt3oDTazw1XxpGYHJWL8o3LTGzVkU",
    "ModalCell_joinRow__sUQiU": "PLY",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "Plenty PLY",
    "Price": 0.0018,
    "Full name": "Bribe for CTez/PLY Plenty Network",
    "contract address": "KT1JVjgXPMMSaa6FkzeJcgb8q9cUaLmwaJUX",
    "contract address__1": "KT1JVjgXPMMSaa6FkzeJcgb8q9cUaLmwaJUX",
    "token id": null,
    "total supply": 243000000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 1894,
    "mcap": 437_400.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmb9QUXYn1PW8e7E2CwpBMgEur7gFAPPpq2Zh7H2D7eQcT",
    "ModalCell_joinRow__sUQiU": "TKEY",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Temple Key",
    "Price": 0.03,
    "Full name": "Quipuswap TKEY_OLD",
    "contract address": "KT1VaEsVNiBoA56eToEK6n6BcPgh1tdx9eXi_0",
    "contract address__1": "KT1VaEsVNiBoA56eToEK6n6BcPgh1tdx9eXi",
    "token id": 0,
    "total supply": 1.4e+25,
    "decimals": 18,
    "Alias": "Temple Key",
    "thumbnailUri": "ipfs://Qmb9QUXYn1PW8e7E2CwpBMgEur7gFAPPpq2Zh7H2D7eQcT",
    "holdersCount": 2388,
    "mcap": 420_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmUWhCYXtC8r8aXgjrwsLrZmopiGMHdLWoQzEueAktJbHB",
    "ModalCell_joinRow__sUQiU": "wTEZ",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped Te...",
    "Price": 0.84,
    "Full name": "wTEZ price provider",
    "contract address": "KT1UpeXdK6AJbX58GJ92pLZVCucn2DR8Nu4b_0",
    "contract address__1": "KT1UpeXdK6AJbX58GJ92pLZVCucn2DR8Nu4b",
    "token id": 0,
    "total supply": 396561734974,
    "decimals": 6,
    "Alias": "Wrapped Tezos FA2 token",
    "thumbnailUri": "ipfs://QmUWhCYXtC8r8aXgjrwsLrZmopiGMHdLWoQzEueAktJbHB",
    "holdersCount": 204,
    "mcap": 333_111.86
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmRB63vb8ThpmxHKF4An3XD8unHyCUuLYm5bZNhXwU4gAZ",
    "ModalCell_joinRow__sUQiU": "wBUSD",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped BUSD",
    "Price": 1.06,
    "Full name": "cTEZ / wBUSD  LP farm",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 1,
    "total supply": 2.8986803177138348e+23,
    "decimals": 18,
    "Alias": "Wrapped BUSD",
    "thumbnailUri": "ipfs://QmRB63vb8ThpmxHKF4An3XD8unHyCUuLYm5bZNhXwU4gAZ",
    "holdersCount": 1489,
    "mcap": 307_260.11
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmb2GiHN9EjcrN29J6y9PsXu3ZDosXTv6uLUWGZfRRSzS2/usdtz.png",
    "ModalCell_joinRow__sUQiU": "USDtz",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "USDtez",
    "Price": 0.99,
    "Full name": "USDtz",
    "contract address": "KT1LN4LPSqTMS7Sd2CJw4bbDGRkMv2t68Fy9",
    "contract address__1": "KT1LN4LPSqTMS7Sd2CJw4bbDGRkMv2t68Fy9",
    "token id": null,
    "total supply": 300000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 2717,
    "mcap": 297_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qme4ybadbY4H84h5WLPjdo47YQUxxVoJHWZrwYq2JZriM4",
    "ModalCell_joinRow__sUQiU": "ctez",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "Ctez",
    "Price": 0.98,
    "Full name": "Ctez",
    "contract address": "KT1SjXiUX63QvdNMcM2m492f7kuf8JxXRLp4",
    "contract address__1": "KT1SjXiUX63QvdNMcM2m492f7kuf8JxXRLp4",
    "token id": null,
    "total supply": 300000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 6240,
    "mcap": 294_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmb2GiHN9EjcrN29J6y9PsXu3ZDosXTv6uLUWGZfRRSzS2/quipu.png",
    "ModalCell_joinRow__sUQiU": "QUIPU",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Quipuswap ...",
    "Price": 0.13,
    "Full name": "QUIPU",
    "contract address": "KT193D4vozYnhGJQVtw7CoxxqphqUEEwK6Vb_0",
    "contract address__1": "KT193D4vozYnhGJQVtw7CoxxqphqUEEwK6Vb",
    "token id": 0,
    "total supply": 2210352101281,
    "decimals": 6,
    "Alias": "Quipuswap Governance Token",
    "thumbnailUri": "https://quipuswap.com/tokens/quipu.png",
    "holdersCount": 8492,
    "mcap": 287_345.77
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmPen6FjwcnuN2yin335WA2Ae6j9FrBN17isHs9NGq2b7Q",
    "ModalCell_joinRow__sUQiU": "TEIA",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Teia DAO t...",
    "Price": 0.03,
    "Full name": "Teia Community Marketplace",
    "contract address": "KT1QrtA753MSv8VGxkDrKKyJniG5JtuHHbtV_0",
    "contract address__1": "KT1QrtA753MSv8VGxkDrKKyJniG5JtuHHbtV",
    "token id": 0,
    "total supply": 8000000000000,
    "decimals": 6,
    "Alias": "Teia DAO token",
    "thumbnailUri": "ipfs://QmPen6FjwcnuN2yin335WA2Ae6j9FrBN17isHs9NGq2b7Q",
    "holdersCount": 2745,
    "mcap": 240_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmb2GiHN9EjcrN29J6y9PsXu3ZDosXTv6uLUWGZfRRSzS2/stably.png",
    "ModalCell_joinRow__sUQiU": "USDS",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Stably USD",
    "Price": 1.03,
    "Full name": "USDS",
    "contract address": "KT1REEb5VxWRjcHm5GzDMwErMmNFftsE5Gpf_0",
    "contract address__1": "KT1REEb5VxWRjcHm5GzDMwErMmNFftsE5Gpf",
    "token id": 0,
    "total supply": 232708320000,
    "decimals": 6,
    "Alias": "Stably USD",
    "thumbnailUri": null,
    "holdersCount": 375,
    "mcap": 239_689.57
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qma2o69VRZe8aPsuCUN1VRUE5k67vw2mFDXb35uDkqn17o",
    "ModalCell_joinRow__sUQiU": "WRAP",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrap Gover...",
    "Price": 0.0078,
    "Full name": "Migration PLENTY and WRAP to PLY",
    "contract address": "KT1LRboPna9yQY9BrjtQYDS1DVxhKESK4VVd_0",
    "contract address__1": "KT1LRboPna9yQY9BrjtQYDS1DVxhKESK4VVd",
    "token id": 0,
    "total supply": 2586617769059839,
    "decimals": 8,
    "Alias": "Wrap Governance Token",
    "thumbnailUri": "ipfs://Qma2o69VRZe8aPsuCUN1VRUE5k67vw2mFDXb35uDkqn17o",
    "holdersCount": 1787,
    "mcap": 201_756.19
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmeaRuB578Xgy8jxbTxqmQ9s5wyioAEP85V7qbJFnn2uT8",
    "ModalCell_joinRow__sUQiU": "wLINK",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped LINK",
    "Price": 14.16,
    "Full name": "PLENTY / wLINK LP farm",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 10,
    "total supply": 1.4203355884512847e+22,
    "decimals": 18,
    "Alias": "Wrapped LINK",
    "thumbnailUri": "ipfs://QmeaRuB578Xgy8jxbTxqmQ9s5wyioAEP85V7qbJFnn2uT8",
    "holdersCount": 887,
    "mcap": 201_119.52
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://kolibri-data.s3.amazonaws.com/kdao-logo.png",
    "ModalCell_joinRow__sUQiU": "kDAO",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "Kolibri DAO",
    "Price": 0.19,
    "Full name": "kDAO",
    "contract address": "KT1JkoE42rrMBP9b2oDhbx6EUr26GcySZMUH",
    "contract address__1": "KT1JkoE42rrMBP9b2oDhbx6EUr26GcySZMUH",
    "token id": null,
    "total supply": 1000000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 1093,
    "mcap": 190_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmVbiHa37pe2U9FfXBYfvrLNpb38rbXwaN19HwZD2speFA",
    "ModalCell_joinRow__sUQiU": "wUSDT",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped USDT",
    "Price": 1.16,
    "Full name": "cTEZ / wUSDT  LP farm",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 18,
    "total supply": 120852313751,
    "decimals": 6,
    "Alias": "Wrapped USDT",
    "thumbnailUri": "ipfs://QmVbiHa37pe2U9FfXBYfvrLNpb38rbXwaN19HwZD2speFA",
    "holdersCount": 796,
    "mcap": 140_188.68
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmb2GiHN9EjcrN29J6y9PsXu3ZDosXTv6uLUWGZfRRSzS2/ethtz.png",
    "ModalCell_joinRow__sUQiU": "ETHtz",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "ETHtez",
    "Price": 1_912.24000000000,
    "Full name": "ETHtz",
    "contract address": "KT19at7rQUvyjxnZ2fBv7D9zc8rkyG7gAoU8",
    "contract address__1": "KT19at7rQUvyjxnZ2fBv7D9zc8rkyG7gAoU8",
    "token id": null,
    "total supply": 60,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 756,
    "mcap": 114_734.40
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeic4zn6dqvbzfdsnlr7hbmddpl65i6hfmt6b2dppjxy3tako3vmovy",
    "ModalCell_joinRow__sUQiU": "USDC.e",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Ethereum U...",
    "Price": 1,
    "Full name": "Bribe for USDT.e/USDC.e Plenty Network",
    "contract address": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY_0",
    "contract address__1": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY",
    "token id": 0,
    "total supply": 103090747892,
    "decimals": 6,
    "Alias": "Ethereum USDC",
    "thumbnailUri": "ipfs://bafybeic4zn6dqvbzfdsnlr7hbmddpl65i6hfmt6b2dppjxy3tako3vmovy",
    "holdersCount": 726,
    "mcap": 103_090.75
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmQxoTVVuFS677TQJFdVh1PNRoBmVbvkwJSxe1xvf9cSqU",
    "ModalCell_joinRow__sUQiU": "GIF",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "GIF DAO",
    "Price": 0.00097,
    "Full name": "GIF / cTEZ  LP farm",
    "contract address": "KT1XTxpQvo7oRCqp85LikEZgAZ22uDxhbWJv_0",
    "contract address__1": "KT1XTxpQvo7oRCqp85LikEZgAZ22uDxhbWJv",
    "token id": 0,
    "total supply": 100000000000000000,
    "decimals": 9,
    "Alias": "GIF DAO",
    "thumbnailUri": "ipfs://QmQxoTVVuFS677TQJFdVh1PNRoBmVbvkwJSxe1xvf9cSqU",
    "holdersCount": 835,
    "mcap": 97_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmchBnjRjpweznHes7bVKHwgzd8D6Q7Yzwf6KmA4KS6Dgi",
    "ModalCell_joinRow__sUQiU": "wMATIC",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped MA...",
    "Price": 0.88,
    "Full name": "PLENTY / wMATIC LP farm",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 11,
    "total supply": 1.0185929563363727e+23,
    "decimals": 18,
    "Alias": "Wrapped MATIC",
    "thumbnailUri": "ipfs://QmchBnjRjpweznHes7bVKHwgzd8D6Q7Yzwf6KmA4KS6Dgi",
    "holdersCount": 930,
    "mcap": 89_636.18
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeidwsid6fvv4vxbqja7er3b4exsht5r7umv6hpz7rc3ujg7xilhwv4",
    "ModalCell_joinRow__sUQiU": "WTZ",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "WTZ",
    "Price": 0.92,
    "Full name": "WTZ",
    "contract address": "KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn_0",
    "contract address__1": "KT1PnUZCp3u2KzWr93pn4DD7HAJnm3rWVrgn",
    "token id": 0,
    "total supply": 95555882574,
    "decimals": 6,
    "Alias": "WTZ",
    "thumbnailUri": "ipfs://bafybeidwsid6fvv4vxbqja7er3b4exsht5r7umv6hpz7rc3ujg7xilhwv4",
    "holdersCount": 2641,
    "mcap": 87_911.41
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmPJ7dMS3T6McqPjjBioKhHqtEUEBhAXpcRf3aicaLNPtV",
    "ModalCell_joinRow__sUQiU": "sDAO",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Salsa DAO",
    "Price": 0.0012,
    "Full name": "QuipuSwap sDAO",
    "contract address": "KT19ovJhcsUn4YU8Q5L3BGovKSixfbWcecEA_1",
    "contract address__1": "KT19ovJhcsUn4YU8Q5L3BGovKSixfbWcecEA",
    "token id": 1,
    "total supply": 57500000,
    "decimals": 0,
    "Alias": "Salsa DAO",
    "thumbnailUri": "ipfs://QmPJ7dMS3T6McqPjjBioKhHqtEUEBhAXpcRf3aicaLNPtV",
    "holdersCount": 551,
    "mcap": 69_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://github.com/StakerDAO/resources/raw/main/stkr.png",
    "ModalCell_joinRow__sUQiU": "STKR",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "Staker Gov...",
    "Price": 0.000187,
    "Full name": "QuipuSwap STKR",
    "contract address": "KT1AEfeckNbdEYwaMKkytBwPJPycz7jdSGea",
    "contract address__1": "KT1AEfeckNbdEYwaMKkytBwPJPycz7jdSGea",
    "token id": null,
    "total supply": 343000000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 866,
    "mcap": 64_141.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmSpZ1rPgHMPpxUsBCFUM7oERHmDVXUz219no27jWqceH6",
    "ModalCell_joinRow__sUQiU": "akaDAO",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "akaSwap DAO",
    "Price": 0.06,
    "Full name": "akaDAO",
    "contract address": "KT1AM3PV1cwmGRw28DVTgsjjsjHvmL6z4rGh_0",
    "contract address__1": "KT1AM3PV1cwmGRw28DVTgsjjsjHvmL6z4rGh",
    "token id": 0,
    "total supply": 1000000000000,
    "decimals": 6,
    "Alias": "akaSwap DAO",
    "thumbnailUri": "ipfs://QmSpZ1rPgHMPpxUsBCFUM7oERHmDVXUz219no27jWqceH6",
    "holdersCount": 4637,
    "mcap": 60_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qma4wzNogtUkuhMgzyKBqzaYBqabLVZrHcLbLmJE38B5XH",
    "ModalCell_joinRow__sUQiU": "PXL",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Pixel",
    "Price": 0.000599,
    "Full name": "PXL",
    "contract address": "KT1F1mn2jbqQCJcsNgYKVAQjvenecNMY2oPK_0",
    "contract address__1": "KT1F1mn2jbqQCJcsNgYKVAQjvenecNMY2oPK",
    "token id": 0,
    "total supply": 100000000000000,
    "decimals": 6,
    "Alias": "Pixel",
    "thumbnailUri": "https://cloudflare-ipfs.com/ipfs/Qma4wzNogtUkuhMgzyKBqzaYBqabLVZrHcLbLmJE38B5XH",
    "holdersCount": 984,
    "mcap": 59_900.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmXhFWvikC87rJGb9Gwc5cYG77rioK2FDBvgx9ej5iuRKG",
    "ModalCell_joinRow__sUQiU": "STARtz",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "STARtz",
    "Price": 0.00097,
    "Full name": "STARtz",
    "contract address": "KT1GS3uEWWVkAxVfq66EtUn1g6uGX1J72K5Y_0",
    "contract address__1": "KT1GS3uEWWVkAxVfq66EtUn1g6uGX1J72K5Y",
    "token id": 0,
    "total supply": 50000000,
    "decimals": 0,
    "Alias": "STARtz",
    "thumbnailUri": "https://ipfs.io/ipfs/QmXhFWvikC87rJGb9Gwc5cYG77rioK2FDBvgx9ej5iuRKG/",
    "holdersCount": 344,
    "mcap": 48_500.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmYMMztcxtohk1t3p4X8DDX45REzeThL1TaJroH5RT5Chj",
    "ModalCell_joinRow__sUQiU": "INSTA",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Instaraise",
    "Price": 0.00048,
    "Full name": "FLAME LP - INSTA Farm",
    "contract address": "KT19y6R8x53uDKiM46ahgguS6Tjqhdj2rSzZ_0",
    "contract address__1": "KT19y6R8x53uDKiM46ahgguS6Tjqhdj2rSzZ",
    "token id": 0,
    "total supply": 100000000000000000,
    "decimals": 9,
    "Alias": "Instaraise",
    "thumbnailUri": "ipfs://QmYMMztcxtohk1t3p4X8DDX45REzeThL1TaJroH5RT5Chj",
    "holdersCount": 499,
    "mcap": 48_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmYQdCWFh26rPoaYNLFBa3mQg3EyXyfgJ5ktG4YrkbD4AZ",
    "ModalCell_joinRow__sUQiU": "SPI",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Spice Token",
    "Price": 0.00042,
    "Full name": "SPI",
    "contract address": "KT1CS2xKGHNPTauSh5Re4qE3N9PCfG5u4dPx_0",
    "contract address__1": "KT1CS2xKGHNPTauSh5Re4qE3N9PCfG5u4dPx",
    "token id": 0,
    "total supply": 100000000000000,
    "decimals": 6,
    "Alias": "Spice Token",
    "thumbnailUri": "ipfs://QmYQdCWFh26rPoaYNLFBa3mQg3EyXyfgJ5ktG4YrkbD4AZ",
    "holdersCount": 446,
    "mcap": 42_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmfAJX4A534cpp2XjDGSM8b8PrqnSt8b7ytuteY8MXkBPD",
    "ModalCell_joinRow__sUQiU": "BTCtz",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "BTCtez",
    "Price": 32_763.39000000000,
    "Full name": "BTCtz",
    "contract address": "KT1T87QbpXEVgkwsNPzz8iRoah3SS3D1MDmh_0",
    "contract address__1": "KT1T87QbpXEVgkwsNPzz8iRoah3SS3D1MDmh",
    "token id": 0,
    "total supply": 118658570,
    "decimals": 8,
    "Alias": "BTCtez",
    "thumbnailUri": "ipfs://QmfAJX4A534cpp2XjDGSM8b8PrqnSt8b7ytuteY8MXkBPD",
    "holdersCount": 91,
    "mcap": 38_876.57
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmPfBrZiRsC39S2VvNbhuxH9HnNcSx8aef9uBCG51J5c4e",
    "ModalCell_joinRow__sUQiU": "hDAO",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "hic et nun...",
    "Price": 0.035,
    "Full name": "hDAO",
    "contract address": "KT1AFA2mwNUMNd4SsujE1YYp29vd8BZejyKW_0",
    "contract address__1": "KT1AFA2mwNUMNd4SsujE1YYp29vd8BZejyKW",
    "token id": 0,
    "total supply": 651099128108,
    "decimals": 6,
    "Alias": "Hic et nunc DAO",
    "thumbnailUri": null,
    "holdersCount": 5711,
    "mcap": 22_788.47
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmXdQ3DaMsnqH7MEhX77foWfjxRnj8Qe88mwekkn4PSt3q",
    "ModalCell_joinRow__sUQiU": "UNO",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Unobtanium",
    "Price": 0.18,
    "Full name": "Particular Uno",
    "contract address": "KT1ErKVqEhG9jxXgUG2KGLW3bNM7zXHX8SDF_0",
    "contract address__1": "KT1ErKVqEhG9jxXgUG2KGLW3bNM7zXHX8SDF",
    "token id": 0,
    "total supply": 85990400830000,
    "decimals": 9,
    "Alias": "Unobtanium",
    "thumbnailUri": "ipfs://QmXdQ3DaMsnqH7MEhX77foWfjxRnj8Qe88mwekkn4PSt3q",
    "holdersCount": 1246,
    "mcap": 15_478.27
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmNwMXAL5tVaPxauq7W4mXMhFGNVsstBfQ87AwUUo94thL",
    "ModalCell_joinRow__sUQiU": "RCKT",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Rocket",
    "Price": 0.00003,
    "Full name": "QuipuSwap RCKT",
    "contract address": "KT19JYndHaesXpvUfiwgg8BtE41HKkjjGMRC_0",
    "contract address__1": "KT19JYndHaesXpvUfiwgg8BtE41HKkjjGMRC",
    "token id": 0,
    "total supply": 500000000000000,
    "decimals": 6,
    "Alias": "Rocket",
    "thumbnailUri": "https://gblobscdn.gitbook.com/assets%2F-MayY_wA8g4oLd9eVN9A%2F-MbbCn2yMCnBWfDTMUTb%2F-MbbDTyyuxM6uBAYA6ms%2FToken.png",
    "holdersCount": 292,
    "mcap": 15_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://i.ibb.co/3m7xx5C/Rocket-9.png",
    "ModalCell_joinRow__sUQiU": "rkDAO",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Rocket DAO",
    "Price": 0.11,
    "Full name": "Quipuswap rkDAO",
    "contract address": "KT1MuyJ7gVw74FNJpfb2mHR15aCREdyEbe2e_0",
    "contract address__1": "KT1MuyJ7gVw74FNJpfb2mHR15aCREdyEbe2e",
    "token id": 0,
    "total supply": 10000000000000,
    "decimals": 8,
    "Alias": "Rocket DAO",
    "thumbnailUri": "https://i.ibb.co/3m7xx5C/Rocket-9.png",
    "holdersCount": 144,
    "mcap": 11_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmdLVzCSS2QRku5ynpcghs8ccn8MjwJtrFCCmSniqoBksV",
    "ModalCell_joinRow__sUQiU": "TCOIN",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "TCOIN",
    "Price": 0.02,
    "Full name": "Quipuswap TCOIN",
    "contract address": "KT1GorwGk5WXLUc3sEWrmPLQBSekmYrtz1sn",
    "contract address__1": "KT1GorwGk5WXLUc3sEWrmPLQBSekmYrtz1sn",
    "token id": null,
    "total supply": 550000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 218,
    "mcap": 11_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cryptoeasy.io/img/cryptoeasy-logo.png",
    "ModalCell_joinRow__sUQiU": "EASY",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "CryptoEasy",
    "Price": 0.0013,
    "Full name": "EASY",
    "contract address": "KT1QgAtLPu3SNq9c6DPLanwL5bvfX3rgh2CS_0",
    "contract address__1": "KT1QgAtLPu3SNq9c6DPLanwL5bvfX3rgh2CS",
    "token id": 0,
    "total supply": 6000000000000,
    "decimals": 6,
    "Alias": "CryptoEasy",
    "thumbnailUri": "https://cryptoeasy.io/img/cryptoeasy-logo.png",
    "holdersCount": 148,
    "mcap": 7_800.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qme9FX9M7o2PZt9h6rvkUbfXoLpQr1HsuMQi6sL5Y75g3A",
    "ModalCell_joinRow__sUQiU": "KALAM",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Kalamint",
    "Price": 0.0005,
    "Full name": "KALAM",
    "contract address": "KT1A5P4ejnLix13jtadsfV9GCnXLMNnab8UT_0",
    "contract address__1": "KT1A5P4ejnLix13jtadsfV9GCnXLMNnab8UT",
    "token id": 0,
    "total supply": 100000000000000000,
    "decimals": 10,
    "Alias": "Kalamint",
    "thumbnailUri": "ipfs://Qme9FX9M7o2PZt9h6rvkUbfXoLpQr1HsuMQi6sL5Y75g3A",
    "holdersCount": 7769,
    "mcap": 5_000.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeibi45na6dimqwdznpj6m254vos6hez7232mqrrbj27xzwsh36gz4i",
    "ModalCell_joinRow__sUQiU": "USDT.e",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Ethereum U...",
    "Price": 1,
    "Full name": "Bribe for USDT.e/USDC.e Plenty Network",
    "contract address": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY_5",
    "contract address__1": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY",
    "token id": 5,
    "total supply": 23525770750,
    "decimals": 6,
    "Alias": "Ethereum USDT",
    "thumbnailUri": "ipfs://bafybeibi45na6dimqwdznpj6m254vos6hez7232mqrrbj27xzwsh36gz4i",
    "holdersCount": 138,
    "mcap": 705.77
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://raw.githubusercontent.com/allbridge-io/media/main/token256.png",
    "ModalCell_joinRow__sUQiU": "ABR",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Allbridge",
    "Price": 0.15,
    "Full name": "Abraham Maramis",
    "contract address": "KT1UG6PdaKoJcc3yD6mkFVfxnS1uJeW3cGeX_0",
    "contract address__1": "KT1UG6PdaKoJcc3yD6mkFVfxnS1uJeW3cGeX",
    "token id": 0,
    "total supply": 20644399819,
    "decimals": 6,
    "Alias": "Allbridge",
    "thumbnailUri": "https://raw.githubusercontent.com/allbridge-io/media/main/token256.png",
    "holdersCount": 46,
    "mcap": 3_096.66
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmRrvFBwRKK8cQ6yKXEX38Q34wrWK6FBbCvQPzun5e4kjP",
    "ModalCell_joinRow__sUQiU": "MTRIA",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Materia",
    "Price": 0.03,
    "Full name": "QuipuSwap MTRIA",
    "contract address": "KT1KRvNVubq64ttPbQarxec5XdS6ZQU4DVD2_0",
    "contract address__1": "KT1KRvNVubq64ttPbQarxec5XdS6ZQU4DVD2",
    "token id": 0,
    "total supply": 94421231710,
    "decimals": 6,
    "Alias": "Materia",
    "thumbnailUri": "ipfs://QmRrvFBwRKK8cQ6yKXEX38Q34wrWK6FBbCvQPzun5e4kjP",
    "holdersCount": 4946,
    "mcap": 2_832.64
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmVUVanUUjHmgkjnUC6TVzG7pPz6iy7C8tnAoXNNpofYPg",
    "ModalCell_joinRow__sUQiU": "wAAVE",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped AAVE",
    "Price": 66.43,
    "Full name": "QuipuSwap wAAVE",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 0,
    "total supply": 34279355644462813000,
    "decimals": 18,
    "Alias": "Wrapped AAVE",
    "thumbnailUri": "ipfs://QmVUVanUUjHmgkjnUC6TVzG7pPz6iy7C8tnAoXNNpofYPg",
    "holdersCount": 658,
    "mcap": 2_277.18
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmQBezdVvotCGnFHgQNKduLdxEJhfgruSEqtwnWY7mESb2",
    "ModalCell_joinRow__sUQiU": "wUNI",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped UNI",
    "Price": 3.09,
    "Full name": "QuipuSwap wUNI",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 16,
    "total supply": 681846793414176400000,
    "decimals": 18,
    "Alias": "Wrapped UNI",
    "thumbnailUri": "ipfs://QmQBezdVvotCGnFHgQNKduLdxEJhfgruSEqtwnWY7mESb2",
    "holdersCount": 641,
    "mcap": 2_106.91
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://raw.githubusercontent.com/allbridge-io/media/main/usdc256.png",
    "ModalCell_joinRow__sUQiU": "apUSDC",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Allbridge ...",
    "Price": 1.09,
    "Full name": "Quipuswap apUSDC",
    "contract address": "KT1UG6PdaKoJcc3yD6mkFVfxnS1uJeW3cGeX_2",
    "contract address__1": "KT1UG6PdaKoJcc3yD6mkFVfxnS1uJeW3cGeX",
    "token id": 2,
    "total supply": 1649458335,
    "decimals": 6,
    "Alias": "Allbridge Wrapped Polygon USDC",
    "thumbnailUri": "https://raw.githubusercontent.com/allbridge-io/media/main/usdc256.png",
    "holdersCount": 196,
    "mcap": 1_797.91
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmNfosyixuXVG2TGmE7FmLGZGJhK2Q9qHZicsMixsbgqH1",
    "ModalCell_joinRow__sUQiU": "uDEFI",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "youves uDEFI",
    "Price": 0.22,
    "Full name": "QuipuSwap uDEFI",
    "contract address": "KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW_1",
    "contract address__1": "KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW",
    "token id": 1,
    "total supply": 7000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 0,
    "mcap": 1_540.00
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmZD5QDAeAUyyLYKiMmxD4vfWpVeYHctcbTkPmo4NudDHt",
    "ModalCell_joinRow__sUQiU": "wPAX",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped PAX",
    "Price": 0.43,
    "Full name": "QuipuSwap wPAX",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 14,
    "total supply": 2.8188180907047146e+21,
    "decimals": 18,
    "Alias": "Wrapped PAX",
    "thumbnailUri": "ipfs://QmZD5QDAeAUyyLYKiMmxD4vfWpVeYHctcbTkPmo4NudDHt",
    "holdersCount": 598,
    "mcap": 1_212.09
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeienhhbxz53n3gtg7stjou2zs3lmhupahwovv2kxwh5uass3bc5xzq",
    "ModalCell_joinRow__sUQiU": "CRUNCH",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "CRUNCH",
    "Price": 0.0000091,
    "Full name": "CRUNCH",
    "contract address": "KT1BHCumksALJQJ8q8to2EPigPW6qpyTr7Ng_0",
    "contract address__1": "KT1BHCumksALJQJ8q8to2EPigPW6qpyTr7Ng",
    "token id": 0,
    "total supply": 10000000000000000,
    "decimals": 8,
    "Alias": null,
    "thumbnailUri": "ipfs://bafybeienhhbxz53n3gtg7stjou2zs3lmhupahwovv2kxwh5uass3bc5xzq",
    "holdersCount": 1775,
    "mcap": 910
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmUYksqRFqUA5LUfxFs1oWLmP8Ti2SdyPAq5u72aAQLN7D",
    "ModalCell_joinRow__sUQiU": "MCH",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Machinery",
    "Price": 0.0000049,
    "Full name": "QuipuSwap MCH",
    "contract address": "KT1ErKVqEhG9jxXgUG2KGLW3bNM7zXHX8SDF_3",
    "contract address__1": "KT1ErKVqEhG9jxXgUG2KGLW3bNM7zXHX8SDF",
    "token id": 3,
    "total supply": 130091104166562500,
    "decimals": 9,
    "Alias": "Machinery",
    "thumbnailUri": "ipfs://QmUYksqRFqUA5LUfxFs1oWLmP8Ti2SdyPAq5u72aAQLN7D",
    "holdersCount": 1132,
    "mcap": 637.45
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://raw.githubusercontent.com/allbridge-io/media/main/busd256.png",
    "ModalCell_joinRow__sUQiU": "abBUSD",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Allbridge ...",
    "Price": 1.04,
    "Full name": "QuipuSwap abUSDC/abBUSD/USDT Farm 2.0",
    "contract address": "KT1UG6PdaKoJcc3yD6mkFVfxnS1uJeW3cGeX_1",
    "contract address__1": "KT1UG6PdaKoJcc3yD6mkFVfxnS1uJeW3cGeX",
    "token id": 1,
    "total supply": 514783246,
    "decimals": 6,
    "Alias": "Allbridge Wrapped BUSD",
    "thumbnailUri": "https://raw.githubusercontent.com/allbridge-io/media/main/busd256.png",
    "holdersCount": 148,
    "mcap": 535.37
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeihluaaujem7nrt36bkhhfjl6wbkqugpt3hipgofh3vdui24wseupy",
    "ModalCell_joinRow__sUQiU": "MATIC.e",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Ethereum M...",
    "Price": 0.87,
    "Full name": "Bribe for MATIC.e/CTez Plenty Network",
    "contract address": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY_6",
    "contract address__1": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY",
    "token id": 6,
    "total supply": 1.4398621537129204e+22,
    "decimals": 18,
    "Alias": "Ethereum MATIC",
    "thumbnailUri": "ipfs://bafybeihluaaujem7nrt36bkhhfjl6wbkqugpt3hipgofh3vdui24wseupy",
    "holdersCount": 152,
    "mcap": 0.07
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmVMyqkFKAeyfGBeR81h72ugqj4UM8hjqA7KaKcnc35Vtt",
    "ModalCell_joinRow__sUQiU": "bDAO",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Bazaar DAO",
    "Price": 0.00081,
    "Full name": "bDAO",
    "contract address": "KT1GUNKmkrgtMQjJp3XxcmCj6HZBhkUmMbge_0",
    "contract address__1": "KT1GUNKmkrgtMQjJp3XxcmCj6HZBhkUmMbge",
    "token id": 0,
    "total supply": 500000000000,
    "decimals": 6,
    "Alias": "Bazaar DAO",
    "thumbnailUri": "ipfs://QmVMyqkFKAeyfGBeR81h72ugqj4UM8hjqA7KaKcnc35Vtt",
    "holdersCount": 406,
    "mcap": 405
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmTpss9a4uL3op7x5Lte7CcTKUSUhZsM1Gr34BWNvZCfy4",
    "ModalCell_joinRow__sUQiU": "wSUSHI",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped SU...",
    "Price": 0.43,
    "Full name": "QuipuSwap wSUSHI",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 15,
    "total supply": 281055910671936000000,
    "decimals": 18,
    "Alias": "Wrapped SUSHI",
    "thumbnailUri": "ipfs://QmTpss9a4uL3op7x5Lte7CcTKUSUhZsM1Gr34BWNvZCfy4",
    "holdersCount": 645,
    "mcap": 120.85
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmT9bozupnmWjmjnXp8KcZqDY9HYLLr5KgojfxqgoWRgCt",
    "ModalCell_joinRow__sUQiU": "wHUSD",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped HUSD",
    "Price": 0.03,
    "Full name": "QuipuSwap wHUSD",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 8,
    "total supply": 348397372116,
    "decimals": 8,
    "Alias": "Wrapped HUSD",
    "thumbnailUri": "ipfs://QmT9bozupnmWjmjnXp8KcZqDY9HYLLr5KgojfxqgoWRgCt",
    "holdersCount": 623,
    "mcap": 104.52
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmZe16xqundEf6JcRuct6gmoUE7wQM5cNHWPLrZhUY3v6Z",
    "ModalCell_joinRow__sUQiU": "uXTZ",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "youves uXTZ",
    "Price": 0.84,
    "Full name": "Bribe for uXAU/uXTZ Plenty Network",
    "contract address": "KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW_3",
    "contract address__1": "KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW",
    "token id": 3,
    "total supply": 112789496626303,
    "decimals": 12,
    "Alias": "youves uBTC",
    "thumbnailUri": null,
    "holdersCount": 724,
    "mcap": 94.74
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmVBjgrJiUynv72MR6rRyUu1WLKX52bWGiKk7H2CaFDRNW",
    "ModalCell_joinRow__sUQiU": "wFTT",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped FTT",
    "Price": 1.15,
    "Full name": "QuipuSwap wFTT",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 6,
    "total supply": 30009667729248862000,
    "decimals": 18,
    "Alias": "Wrapped FTT",
    "thumbnailUri": "ipfs://QmVBjgrJiUynv72MR6rRyUu1WLKX52bWGiKk7H2CaFDRNW",
    "holdersCount": 661,
    "mcap": 34.51
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeidzwaurmronh7acpctit44q53riuwjsvp6b2r4hxublkeb3zhlkru",
    "ModalCell_joinRow__sUQiU": "BUSD.e",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Ethereum B...",
    "Price": 0.85,
    "Full name": "BUSD.e-USDC.e Plenty Stable swap",
    "contract address": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY_3",
    "contract address__1": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY",
    "token id": 3,
    "total supply": 1.7858962525536347e+22,
    "decimals": 18,
    "Alias": "Ethereum BUSD",
    "thumbnailUri": "ipfs://bafybeidzwaurmronh7acpctit44q53riuwjsvp6b2r4hxublkeb3zhlkru",
    "holdersCount": 163,
    "mcap": 249_311.12
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeia7grvsvx2tno4qmwcatsnfdo7whi3elp2xidvg6iqxqkm4in2ife",
    "ModalCell_joinRow__sUQiU": "WBTC.e",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Ethereum W...",
    "Price": 36_472.63000000000,
    "Full name": "Bribe for tzBTC/WBTC.e Plenty Network",
    "contract address": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY_2",
    "contract address__1": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY",
    "token id": 2,
    "total supply": 863360064,
    "decimals": 8,
    "Alias": "Ethereum WBTC",
    "thumbnailUri": "ipfs://bafybeia7grvsvx2tno4qmwcatsnfdo7whi3elp2xidvg6iqxqkm4in2ife",
    "holdersCount": 159,
    "mcap": 9.93
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeic4q4bet3il3gdwgjqxs4i2czi6uujbyltan7liat5oyxmccp5sce",
    "ModalCell_joinRow__sUQiU": "LINK.e",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Ethereum L...",
    "Price": 13.96,
    "Full name": "QuipuSwap LINK.e",
    "contract address": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY_7",
    "contract address__1": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY",
    "token id": 7,
    "total supply": 2.704737102292214e+21,
    "decimals": 18,
    "Alias": "Ethereum LINK",
    "thumbnailUri": "ipfs://bafybeic4q4bet3il3gdwgjqxs4i2czi6uujbyltan7liat5oyxmccp5sce",
    "holdersCount": 103,
    "mcap": 2_271.98
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmfNuyU3V6XeS9PgVXMDq4h5ux1VciUXtApP2ZGC4VSGLd",
    "ModalCell_joinRow__sUQiU": "wCEL",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped CEL",
    "Price": 0.0028,
    "Full name": "ArtExcel",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 2,
    "total supply": 4020041,
    "decimals": 4,
    "Alias": "Wrapped CEL",
    "thumbnailUri": "ipfs://QmfNuyU3V6XeS9PgVXMDq4h5ux1VciUXtApP2ZGC4VSGLd",
    "holdersCount": 554,
    "mcap": 1.13
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeicqbt2gepdljrjpcsaypkyjhbmuvra6jkpcwmmw6qgtwfu7dcdezy",
    "ModalCell_joinRow__sUQiU": "DAI.e",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Ethereum DAI",
    "Price": 0.98,
    "Full name": "QuipuSwap DAI.e",
    "contract address": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY_4",
    "contract address__1": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY",
    "token id": 4,
    "total supply": 8.810840616365032e+21,
    "decimals": 18,
    "Alias": "Ethereum DAI",
    "thumbnailUri": "ipfs://bafybeicqbt2gepdljrjpcsaypkyjhbmuvra6jkpcwmmw6qgtwfu7dcdezy",
    "holdersCount": 82,
    "mcap": 9.08
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/bafybeieqpwi26snvx5gxhcmuv3lomi34iljayzawoa6gewosmviu4ii2bi",
    "ModalCell_joinRow__sUQiU": "WETH.e",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Ethereum W...",
    "Price": 1_967.33000000000,
    "Full name": "QuipuSwap WETH.e",
    "contract address": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY_1",
    "contract address__1": "KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY",
    "token id": 1,
    "total supply": 55576068594156090000,
    "decimals": 18,
    "Alias": "Ethereum WETH",
    "thumbnailUri": "ipfs://bafybeieqpwi26snvx5gxhcmuv3lomi34iljayzawoa6gewosmviu4ii2bi",
    "holdersCount": 267,
    "mcap": 0.06
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmPTob6YP9waErN4gMXqHg6ZyazSFB9CEojot4BB2XPpZJ",
    "ModalCell_joinRow__sUQiU": "wMKR",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped MKR",
    "Price": 0.00103,
    "Full name": "QuipuSwap wMKR",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 12,
    "total supply": 855327737194690300,
    "decimals": 18,
    "Alias": "Wrapped MKR",
    "thumbnailUri": "ipfs://QmPTob6YP9waErN4gMXqHg6ZyazSFB9CEojot4BB2XPpZJ",
    "holdersCount": 663,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmYy2jUUE69W5eE9uwh4x5LqUxHt3GVy8sjXHhpViqCspG",
    "ModalCell_joinRow__sUQiU": "wCOMP",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped COMP",
    "Price": 0,
    "Full name": "QuipuSwap wCOMP",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 3,
    "total supply": 7798299202315263000,
    "decimals": 18,
    "Alias": "Wrapped COMP",
    "thumbnailUri": "ipfs://QmYy2jUUE69W5eE9uwh4x5LqUxHt3GVy8sjXHhpViqCspG",
    "holdersCount": 665,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmUuhxgCm2EXwddpU8ofBBh9z1qzxf2BJRbxxR1ebYr8Hd",
    "ModalCell_joinRow__sUQiU": "wCRO",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped CRO",
    "Price": 0.09,
    "Full name": "QuipuSwap wCRO",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 4,
    "total supply": 8504907238232,
    "decimals": 8,
    "Alias": "Wrapped CRO",
    "thumbnailUri": "ipfs://QmUuhxgCm2EXwddpU8ofBBh9z1qzxf2BJRbxxR1ebYr8Hd",
    "holdersCount": 619,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmVov6RtfRNzuQGvGKmhnABUsfCiDKvn31amg8DUxzowtM",
    "ModalCell_joinRow__sUQiU": "wDAI",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped DAI",
    "Price": 0.99,
    "Full name": "cTEZ / wDAI  LP farm",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 5,
    "total supply": 1.0417341014125122e+23,
    "decimals": 18,
    "Alias": "Wrapped DAI",
    "thumbnailUri": "ipfs://QmVov6RtfRNzuQGvGKmhnABUsfCiDKvn31amg8DUxzowtM",
    "holdersCount": 1059,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmayt4JbYTkQinNUeVGLhp51LTRMD1273HRgo9p96SoQaM",
    "ModalCell_joinRow__sUQiU": "wHT",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped HT",
    "Price": 0,
    "Full name": "QuipuSwap wHT",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 7,
    "total supply": 59699467914408845000,
    "decimals": 18,
    "Alias": "Wrapped HT",
    "thumbnailUri": "ipfs://Qmayt4JbYTkQinNUeVGLhp51LTRMD1273HRgo9p96SoQaM",
    "holdersCount": 661,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmPpmuLw4i9qJLMmGjXrGxrcPBwTiNZgLGuh7kYXeyTdyA",
    "ModalCell_joinRow__sUQiU": "wOKB",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped OKB",
    "Price": 0,
    "Full name": "QuipuSwap wOKB",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 13,
    "total supply": 42166327379821350000,
    "decimals": 18,
    "Alias": "Wrapped OKB",
    "thumbnailUri": "ipfs://QmPpmuLw4i9qJLMmGjXrGxrcPBwTiNZgLGuh7kYXeyTdyA",
    "holdersCount": 673,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmPrmELnhSoheHCHx6XcjSera7f89NYmXabBnSRSCdDjBh",
    "ModalCell_joinRow__sUQiU": "wLEO",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Wrapped LEO",
    "Price": 0,
    "Full name": "QuipuSwap wLEO",
    "contract address": "",
    "contract address__1": "KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ",
    "token id": 9,
    "total supply": 228191800012206870000,
    "decimals": 18,
    "Alias": "Wrapped LEO",
    "thumbnailUri": "ipfs://QmPrmELnhSoheHCHx6XcjSera7f89NYmXabBnSRSCdDjBh",
    "holdersCount": 679,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://tezid.net/idz.png",
    "ModalCell_joinRow__sUQiU": "IDZ",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "TezID",
    "Price": 0,
    "Full name": "IDZ",
    "contract address": "KT1WapdVeFqhCfqwdHWwTzSTX7yXoHgiPRPU_0",
    "contract address__1": "KT1WapdVeFqhCfqwdHWwTzSTX7yXoHgiPRPU",
    "token id": 0,
    "total supply": 1000000000000000,
    "decimals": 8,
    "Alias": "TezID",
    "thumbnailUri": "https://tezid.net/idz.png",
    "holdersCount": 1345,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://raw.githubusercontent.com/Plenty-DeFi/Plenty-Logo/main/xPlenty.png",
    "ModalCell_joinRow__sUQiU": "xPLENTY",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "xPLENTY",
    "Price": 0,
    "Full name": "xPLENTY",
    "contract address": "KT1Rpviewjg82JgjGfAKFneSupjAR1kUhbza",
    "contract address__1": "KT1Rpviewjg82JgjGfAKFneSupjAR1kUhbza",
    "token id": null,
    "total supply": 1876000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": 3352,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmeoZ5ZnGnCMq8iGPeBjoS628c526DR37jnDstqEnTfkwC",
    "ModalCell_joinRow__sUQiU": "PAUL",
    "bage_bage__5REuC": "FA 1.2",
    "ModalCell_caption__k4AvR": "PAUL Token",
    "Price": 0,
    "Full name": "Ale Paul",
    "contract address": "KT19DUSZw7mfeEATrbWVPHRrWNVbNnmfFAE6",
    "contract address__1": "KT19DUSZw7mfeEATrbWVPHRrWNVbNnmfFAE6",
    "token id": null,
    "total supply": 7700000,
    "decimals": 0,
    "Alias": null,
    "thumbnailUri": null,
    "holdersCount": null,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmXJdLDEec56EfJVtWW2XRcYBfkmWVHbCRBDAi7YTigisB",
    "ModalCell_joinRow__sUQiU": "MIN",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Minerals",
    "Price": 0,
    "Full name": "minmin",
    "contract address": "KT1ErKVqEhG9jxXgUG2KGLW3bNM7zXHX8SDF_1",
    "contract address__1": "KT1ErKVqEhG9jxXgUG2KGLW3bNM7zXHX8SDF",
    "token id": 1,
    "total supply": 225988757050937500,
    "decimals": 9,
    "Alias": "Minerals",
    "thumbnailUri": "ipfs://QmXJdLDEec56EfJVtWW2XRcYBfkmWVHbCRBDAi7YTigisB",
    "holdersCount": 1167,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/QmVjjDCrjBkETrWgXeL8NDg4DG2Qbi2hdQRpnWiCdS4qwg",
    "ModalCell_joinRow__sUQiU": "ENR",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Energy",
    "Price": 0,
    "Full name": "QuipuSwap ENR",
    "contract address": "KT1ErKVqEhG9jxXgUG2KGLW3bNM7zXHX8SDF_2",
    "contract address__1": "KT1ErKVqEhG9jxXgUG2KGLW3bNM7zXHX8SDF",
    "token id": 2,
    "total supply": 436686000000000000,
    "decimals": 9,
    "Alias": "Energy",
    "thumbnailUri": "ipfs://QmVjjDCrjBkETrWgXeL8NDg4DG2Qbi2hdQRpnWiCdS4qwg",
    "holdersCount": 1384,
    "mcap": 0
  },
  {
    "token-logo_image__g2g-4 src": "https://img.templewallet.com/insecure/fill/50/50/ce/0/plain/https://cloudflare-ipfs.com/ipfs/Qmb9QUXYn1PW8e7E2CwpBMgEur7gFAPPpq2Zh7H2D7eQcT",
    "ModalCell_joinRow__sUQiU": "Old TKEY",
    "bage_bage__5REuC": "FA 2.0",
    "ModalCell_caption__k4AvR": "Old Temple...",
    "Price": 0,
    "Full name": "Temple Key Old",
    "contract address": "KT1WihWRnmzhfebi6zqQ4tvNGiPeVxiGwTi2_0",
    "contract address__1": "KT1WihWRnmzhfebi6zqQ4tvNGiPeVxiGwTi2",
    "token id": 0,
    "total supply": 1.8095581730968105e+27,
    "decimals": 18,
    "Alias": "Temple Key Old",
    "thumbnailUri": "ipfs://Qmb9QUXYn1PW8e7E2CwpBMgEur7gFAPPpq2Zh7H2D7eQcT",
    "holdersCount": 269,
    "mcap": 0
  }
]

export default (async ({ pageSize }) => {
  return {
    stats : {
      normalFee: '001500', // 0.0015 XTZ // TODO
      lastBlockNumber: (await rpc.getBlockNumber())?.toString() ?? null,
      lastBlockDate: await tzstats.getBlockDate(),
    },
    collections: {
      trending: await objkt.getTopNftCollection(pageSize, 'trending'), // paginated
      top: await objkt.getTopNftCollection(pageSize, 'top'), // paginated
    },
    // TODO: should fetch **tokens on the blockchain**, not coins
    coins: {
      byCap: topTokens.map(token => ({
        contractId: token["contract address__1"],
        id: token["contract address__1"] + (token["token id"] ? '_' + token["token id"] : ''),
        name: token["Full name"] || token["Alias"],
        ticker: token["ModalCell_joinRow__sUQiU"],
        decimals: token["decimals"], // NB: decimals from the scrapping are not reliable
        logo: token["token-logo_image__g2g-4 src"],
        lastPrice: token["Price"],
        circulatingSupplyOnChain: BigInt(Math.round(token["total supply"])).toString(),
        holders: BigInt(Math.round(token["holdersCount"])).toString(),
        capitalizationOnChain: token.mcap,
      })).sort((a, b) => +b.holders - +a.holders),
      byVolume: [],// await coinmarketcap.getTop50Cryptos('volume_24h'), // paginated
    },
  }
}) as HomeEndpoint
